stages:
  BMIM_BF4_363_15K:
    cmd: zntrack run ipsuite.data_loading.add_data_ase.AddData --name BMIM_BF4_363_15K
    deps:
    - data/BMIM_BF4_363_15K.extxyz
    metrics:
    - nodes/BMIM_BF4_363_15K/node-meta.json:
        cache: false
    outs:
    - nodes/BMIM_BF4_363_15K/frames.h5
    params:
    - BMIM_BF4_363_15K
  gromacs_Smiles2Gromacs:
    cmd: zntrack run ipsuite.configuration_generation.gmx.Smiles2Gromacs --name gromacs_Smiles2Gromacs
    deps:
    - config/gromacs/gmx_md.mdp
    metrics:
    - nodes/gromacs/Smiles2Gromacs/node-meta.json:
        cache: false
    outs:
    - nodes/gromacs/Smiles2Gromacs/gromacs
    - nodes/gromacs/Smiles2Gromacs/structures.h5
    params:
    - config/gromacs/gmx_em.yaml: null
    - gromacs_Smiles2Gromacs
  pack_MultiPackmol:
    cmd: zntrack run ipsuite.configuration_generation.packmol.MultiPackmol --name
      pack_MultiPackmol
    deps:
    - nodes/pack/Smiles2Conformers/frames.h5
    metrics:
    - nodes/pack/MultiPackmol/node-meta.json:
        cache: false
    outs:
    - nodes/pack/MultiPackmol/frames.h5
    params:
    - pack_MultiPackmol
  pack_Smiles2Conformers:
    cmd: zntrack run ipsuite.configuration_generation.smiles_to_atoms.Smiles2Conformers
      --name pack_Smiles2Conformers
    metrics:
    - nodes/pack/Smiles2Conformers/node-meta.json:
        cache: false
    outs:
    - nodes/pack/Smiles2Conformers/frames.h5
    params:
    - pack_Smiles2Conformers
  water:
    cmd: zntrack run ipsuite.data_loading.add_data_h5md.AddDataH5MD --name water
    deps:
    - data/water.h5
    metrics:
    - nodes/water/node-meta.json:
        cache: false
