BMIM_BF4_363_15K:
  lines_to_read: null
gromacs_Smiles2Gromacs:
  cleanup: true
  count:
  - 16
  - 16
  density: 0.9
  fudgeLJ: 1.0
  fudgeQQ: 1.0
  labels:
  - Imx
  - BFx
  production_indices:
  - 1
  smiles:
  - CCCCN1C=C[N+](=C1)C
  - CC(=O)[O-]
  tolerance: 2.0
pack_MultiPackmol:
  count:
  - 16
  data_ids: null
  density: 800
  n_configurations: 10
  pbc: true
  seed: 42
  tolerance: 2.0
pack_Smiles2Conformers:
  cell: 100
  maxAttempts: 1000
  numConfs: 10
  seed: 42
  smiles: CCO
